/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __G_CCLOSURE_USER_MARSHAL_MARSHAL_H__
#define __G_CCLOSURE_USER_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* BOOLEAN:BOXED (gtkmarshalers.list:24) */
extern
void g_cclosure_user_marshal_BOOLEAN__BOXED (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* BOOLEAN:BOXED,BOXED (gtkmarshalers.list:25) */
#define g_cclosure_user_marshal_BOOLEAN__BOXED_BOXED	g_cclosure_marshal_BOOLEAN__BOXED_BOXED

/* BOOLEAN:ENUM (gtkmarshalers.list:26) */
extern
void g_cclosure_user_marshal_BOOLEAN__ENUM (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* BOOLEAN:ENUM,BOOLEAN (gtkmarshalers.list:27) */
extern
void g_cclosure_user_marshal_BOOLEAN__ENUM_BOOLEAN (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOOLEAN:ENUM,DOUBLE (gtkmarshalers.list:28) */
extern
void g_cclosure_user_marshal_BOOLEAN__ENUM_DOUBLE (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* BOOLEAN:ENUM,INT (gtkmarshalers.list:29) */
extern
void g_cclosure_user_marshal_BOOLEAN__ENUM_INT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* BOOLEAN:OBJECT (gtkmarshalers.list:30) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* BOOLEAN:OBJECT,UINT,FLAGS (gtkmarshalers.list:31) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_UINT_FLAGS (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* BOOLEAN:OBJECT,INT,INT,UINT (gtkmarshalers.list:32) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_INT_INT_UINT (GClosure     *closure,
                                                           GValue       *return_value,
                                                           guint         n_param_values,
                                                           const GValue *param_values,
                                                           gpointer      invocation_hint,
                                                           gpointer      marshal_data);

/* BOOLEAN:OBJECT,STRING,STRING,BOXED (gtkmarshalers.list:33) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_STRING_STRING_BOXED (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* BOOLEAN:OBJECT,BOXED (gtkmarshalers.list:34) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_BOXED (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOOLEAN:OBJECT,BOXED,BOXED (gtkmarshalers.list:35) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_BOXED_BOXED (GClosure     *closure,
                                                          GValue       *return_value,
                                                          guint         n_param_values,
                                                          const GValue *param_values,
                                                          gpointer      invocation_hint,
                                                          gpointer      marshal_data);

/* BOOLEAN:OBJECT,OBJECT,OBJECT (gtkmarshalers.list:36) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_OBJECT_OBJECT (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* BOOLEAN:OBJECT,STRING,STRING (gtkmarshalers.list:37) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_STRING_STRING (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* BOOLEAN:OBJECT,ENUM (gtkmarshalers.list:38) */
extern
void g_cclosure_user_marshal_BOOLEAN__OBJECT_ENUM (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* BOOLEAN:INT (gtkmarshalers.list:39) */
extern
void g_cclosure_user_marshal_BOOLEAN__INT (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* BOOLEAN:INT,INT (gtkmarshalers.list:40) */
extern
void g_cclosure_user_marshal_BOOLEAN__INT_INT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* BOOLEAN:INT,INT,INT (gtkmarshalers.list:41) */
extern
void g_cclosure_user_marshal_BOOLEAN__INT_INT_INT (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* BOOLEAN:INT,INT,BOOLEAN,OBJECT (gtkmarshalers.list:42) */
extern
void g_cclosure_user_marshal_BOOLEAN__INT_INT_BOOLEAN_OBJECT (GClosure     *closure,
                                                              GValue       *return_value,
                                                              guint         n_param_values,
                                                              const GValue *param_values,
                                                              gpointer      invocation_hint,
                                                              gpointer      marshal_data);

/* BOOLEAN:UINT (gtkmarshalers.list:43) */
extern
void g_cclosure_user_marshal_BOOLEAN__UINT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* BOOLEAN:VOID (gtkmarshalers.list:44) */
extern
void g_cclosure_user_marshal_BOOLEAN__VOID (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* BOOLEAN:BOOLEAN (gtkmarshalers.list:45) */
extern
void g_cclosure_user_marshal_BOOLEAN__BOOLEAN (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* BOOLEAN:BOOLEAN,BOOLEAN,BOOLEAN (gtkmarshalers.list:46) */
extern
void g_cclosure_user_marshal_BOOLEAN__BOOLEAN_BOOLEAN_BOOLEAN (GClosure     *closure,
                                                               GValue       *return_value,
                                                               guint         n_param_values,
                                                               const GValue *param_values,
                                                               gpointer      invocation_hint,
                                                               gpointer      marshal_data);

/* BOOLEAN:STRING (gtkmarshalers.list:47) */
extern
void g_cclosure_user_marshal_BOOLEAN__STRING (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* ENUM:ENUM (gtkmarshalers.list:48) */
extern
void g_cclosure_user_marshal_ENUM__ENUM (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* ENUM:VOID (gtkmarshalers.list:49) */
extern
void g_cclosure_user_marshal_ENUM__VOID (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* INT:POINTER (gtkmarshalers.list:50) */
extern
void g_cclosure_user_marshal_INT__POINTER (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* OBJECT:VOID (gtkmarshalers.list:51) */
extern
void g_cclosure_user_marshal_OBJECT__VOID (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* STRING:DOUBLE (gtkmarshalers.list:52) */
extern
void g_cclosure_user_marshal_STRING__DOUBLE (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* STRING:STRING (gtkmarshalers.list:53) */
extern
void g_cclosure_user_marshal_STRING__STRING (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:DOUBLE (gtkmarshalers.list:54) */
#define g_cclosure_user_marshal_VOID__DOUBLE	g_cclosure_marshal_VOID__DOUBLE

/* VOID:DOUBLE,DOUBLE (gtkmarshalers.list:55) */
extern
void g_cclosure_user_marshal_VOID__DOUBLE_DOUBLE (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:BOOLEAN (gtkmarshalers.list:56) */
#define g_cclosure_user_marshal_VOID__BOOLEAN	g_cclosure_marshal_VOID__BOOLEAN

/* VOID:BOOLEAN,BOOLEAN,BOOLEAN (gtkmarshalers.list:57) */
extern
void g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN_BOOLEAN (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* VOID:BOXED (gtkmarshalers.list:58) */
#define g_cclosure_user_marshal_VOID__BOXED	g_cclosure_marshal_VOID__BOXED

/* VOID:BOXED,BOXED (gtkmarshalers.list:59) */
extern
void g_cclosure_user_marshal_VOID__BOXED_BOXED (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:BOXED,BOXED,POINTER (gtkmarshalers.list:60) */
extern
void g_cclosure_user_marshal_VOID__BOXED_BOXED_POINTER (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* VOID:BOXED,OBJECT (gtkmarshalers.list:61) */
extern
void g_cclosure_user_marshal_VOID__BOXED_OBJECT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:BOXED,STRING,INT (gtkmarshalers.list:62) */
extern
void g_cclosure_user_marshal_VOID__BOXED_STRING_INT (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:BOXED,UINT (gtkmarshalers.list:63) */
extern
void g_cclosure_user_marshal_VOID__BOXED_UINT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:BOXED,UINT,FLAGS (gtkmarshalers.list:64) */
extern
void g_cclosure_user_marshal_VOID__BOXED_UINT_FLAGS (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:BOXED,UINT,UINT (gtkmarshalers.list:65) */
extern
void g_cclosure_user_marshal_VOID__BOXED_UINT_UINT (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* VOID:ENUM (gtkmarshalers.list:66) */
#define g_cclosure_user_marshal_VOID__ENUM	g_cclosure_marshal_VOID__ENUM

/* VOID:ENUM,BOOLEAN (gtkmarshalers.list:67) */
extern
void g_cclosure_user_marshal_VOID__ENUM_BOOLEAN (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:ENUM,ENUM (gtkmarshalers.list:68) */
extern
void g_cclosure_user_marshal_VOID__ENUM_ENUM (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:ENUM,FLOAT (gtkmarshalers.list:69) */
extern
void g_cclosure_user_marshal_VOID__ENUM_FLOAT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:ENUM,FLOAT,BOOLEAN (gtkmarshalers.list:70) */
extern
void g_cclosure_user_marshal_VOID__ENUM_FLOAT_BOOLEAN (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* VOID:ENUM,INT (gtkmarshalers.list:71) */
extern
void g_cclosure_user_marshal_VOID__ENUM_INT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* VOID:ENUM,INT,BOOLEAN (gtkmarshalers.list:72) */
extern
void g_cclosure_user_marshal_VOID__ENUM_INT_BOOLEAN (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:ENUM,INT,INT (gtkmarshalers.list:73) */
extern
void g_cclosure_user_marshal_VOID__ENUM_INT_INT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:ENUM,BOXED (gtkmarshalers.list:74) */
extern
void g_cclosure_user_marshal_VOID__ENUM_BOXED (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:ENUM,STRING (gtkmarshalers.list:75) */
extern
void g_cclosure_user_marshal_VOID__ENUM_STRING (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:FLAGS (gtkmarshalers.list:76) */
#define g_cclosure_user_marshal_VOID__FLAGS	g_cclosure_marshal_VOID__FLAGS

/* VOID:INT (gtkmarshalers.list:77) */
#define g_cclosure_user_marshal_VOID__INT	g_cclosure_marshal_VOID__INT

/* VOID:INT,BOOLEAN (gtkmarshalers.list:78) */
extern
void g_cclosure_user_marshal_VOID__INT_BOOLEAN (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:INT,INT (gtkmarshalers.list:79) */
extern
void g_cclosure_user_marshal_VOID__INT_INT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:INT,INT,BOXED (gtkmarshalers.list:80) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_BOXED (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:INT,INT,INT (gtkmarshalers.list:81) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_INT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:OBJECT (gtkmarshalers.list:82) */
#define g_cclosure_user_marshal_VOID__OBJECT	g_cclosure_marshal_VOID__OBJECT

/* VOID:OBJECT,BOOLEAN (gtkmarshalers.list:83) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:OBJECT,BOXED,BOXED (gtkmarshalers.list:84) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_BOXED_BOXED (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* VOID:OBJECT,BOXED,UINT,UINT (gtkmarshalers.list:85) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_BOXED_UINT_UINT (GClosure     *closure,
                                                           GValue       *return_value,
                                                           guint         n_param_values,
                                                           const GValue *param_values,
                                                           gpointer      invocation_hint,
                                                           gpointer      marshal_data);

/* VOID:OBJECT,BOXED,BOOLEAN,BOOLEAN (gtkmarshalers.list:86) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_BOXED_BOOLEAN_BOOLEAN (GClosure     *closure,
                                                                 GValue       *return_value,
                                                                 guint         n_param_values,
                                                                 const GValue *param_values,
                                                                 gpointer      invocation_hint,
                                                                 gpointer      marshal_data);

/* VOID:OBJECT,ENUM (gtkmarshalers.list:87) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_ENUM (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:OBJECT,FLAGS (gtkmarshalers.list:88) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_FLAGS (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:OBJECT,INT (gtkmarshalers.list:89) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_INT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:OBJECT,INT,OBJECT (gtkmarshalers.list:90) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_INT_OBJECT (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:OBJECT,INT,INT (gtkmarshalers.list:91) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_INT_INT (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:OBJECT,INT,INT,BOXED,UINT,UINT (gtkmarshalers.list:92) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_INT_INT_BOXED_UINT_UINT (GClosure     *closure,
                                                                   GValue       *return_value,
                                                                   guint         n_param_values,
                                                                   const GValue *param_values,
                                                                   gpointer      invocation_hint,
                                                                   gpointer      marshal_data);

/* VOID:OBJECT,OBJECT (gtkmarshalers.list:93) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_OBJECT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:OBJECT,POINTER (gtkmarshalers.list:94) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_POINTER (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);

/* VOID:OBJECT,POINTER,INT (gtkmarshalers.list:95) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_POINTER_INT (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* VOID:OBJECT,STRING (gtkmarshalers.list:96) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_STRING (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:OBJECT,STRING,STRING (gtkmarshalers.list:97) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_STRING_STRING (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:OBJECT,UINT (gtkmarshalers.list:98) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_UINT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:OBJECT,UINT,FLAGS (gtkmarshalers.list:99) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_UINT_FLAGS (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,STRING (gtkmarshalers.list:101) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_OBJECT_STRING (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,OBJECT (gtkmarshalers.list:102) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_OBJECT_OBJECT (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,BOXED,STRING (gtkmarshalers.list:103) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_OBJECT_BOXED_STRING (GClosure     *closure,
                                                               GValue       *return_value,
                                                               guint         n_param_values,
                                                               const GValue *param_values,
                                                               gpointer      invocation_hint,
                                                               gpointer      marshal_data);

/* VOID:OBJECT,OBJECT,POINTER,POINTER (gtkmarshalers.list:104) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_OBJECT_POINTER_POINTER (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* VOID:POINTER (gtkmarshalers.list:105) */
#define g_cclosure_user_marshal_VOID__POINTER	g_cclosure_marshal_VOID__POINTER

/* VOID:POINTER,INT (gtkmarshalers.list:106) */
extern
void g_cclosure_user_marshal_VOID__POINTER_INT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:POINTER,BOOLEAN (gtkmarshalers.list:107) */
extern
void g_cclosure_user_marshal_VOID__POINTER_BOOLEAN (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* VOID:POINTER,POINTER,BOOLEAN (gtkmarshalers.list:108) */
extern
void g_cclosure_user_marshal_VOID__POINTER_POINTER_BOOLEAN (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* VOID:POINTER,POINTER,POINTER (gtkmarshalers.list:109) */
extern
void g_cclosure_user_marshal_VOID__POINTER_POINTER_POINTER (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* VOID:POINTER,UINT (gtkmarshalers.list:110) */
extern
void g_cclosure_user_marshal_VOID__POINTER_UINT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:STRING (gtkmarshalers.list:111) */
#define g_cclosure_user_marshal_VOID__STRING	g_cclosure_marshal_VOID__STRING

/* VOID:STRING,BOXED (gtkmarshalers.list:112) */
extern
void g_cclosure_user_marshal_VOID__STRING_BOXED (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:STRING,STRING (gtkmarshalers.list:113) */
extern
void g_cclosure_user_marshal_VOID__STRING_STRING (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:STRING,STRING,STRING (gtkmarshalers.list:114) */
extern
void g_cclosure_user_marshal_VOID__STRING_STRING_STRING (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:STRING,INT,POINTER (gtkmarshalers.list:115) */
extern
void g_cclosure_user_marshal_VOID__STRING_INT_POINTER (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* VOID:STRING,UINT,FLAGS (gtkmarshalers.list:116) */
extern
void g_cclosure_user_marshal_VOID__STRING_UINT_FLAGS (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:STRING,UINT,FLAGS,UINT (gtkmarshalers.list:117) */
extern
void g_cclosure_user_marshal_VOID__STRING_UINT_FLAGS_UINT (GClosure     *closure,
                                                           GValue       *return_value,
                                                           guint         n_param_values,
                                                           const GValue *param_values,
                                                           gpointer      invocation_hint,
                                                           gpointer      marshal_data);

/* VOID:UINT,FLAGS,BOXED (gtkmarshalers.list:118) */
extern
void g_cclosure_user_marshal_VOID__UINT_FLAGS_BOXED (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:UINT,UINT (gtkmarshalers.list:119) */
extern
void g_cclosure_user_marshal_VOID__UINT_UINT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:UINT,STRING (gtkmarshalers.list:120) */
extern
void g_cclosure_user_marshal_VOID__UINT_STRING (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:UINT,BOXED,UINT,FLAGS,FLAGS (gtkmarshalers.list:121) */
extern
void g_cclosure_user_marshal_VOID__UINT_BOXED_UINT_FLAGS_FLAGS (GClosure     *closure,
                                                                GValue       *return_value,
                                                                guint         n_param_values,
                                                                const GValue *param_values,
                                                                gpointer      invocation_hint,
                                                                gpointer      marshal_data);

/* VOID:UINT,OBJECT,UINT,FLAGS,FLAGS (gtkmarshalers.list:122) */
extern
void g_cclosure_user_marshal_VOID__UINT_OBJECT_UINT_FLAGS_FLAGS (GClosure     *closure,
                                                                 GValue       *return_value,
                                                                 guint         n_param_values,
                                                                 const GValue *param_values,
                                                                 gpointer      invocation_hint,
                                                                 gpointer      marshal_data);

/* VOID:UINT,STRING,UINT (gtkmarshalers.list:123) */
extern
void g_cclosure_user_marshal_VOID__UINT_STRING_UINT (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:VOID (gtkmarshalers.list:125) */
#define g_cclosure_user_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* OBJECT:OBJECT,INT,INT (gtkmarshalers.list:126) */
extern
void g_cclosure_user_marshal_OBJECT__OBJECT_INT_INT (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:OBJECT,STRING,POINTER,POINTER (gtkmarshalers.list:127) */
extern
void g_cclosure_user_marshal_VOID__OBJECT_STRING_POINTER_POINTER (GClosure     *closure,
                                                                  GValue       *return_value,
                                                                  guint         n_param_values,
                                                                  const GValue *param_values,
                                                                  gpointer      invocation_hint,
                                                                  gpointer      marshal_data);

/* INT:INT (gtkmarshalers.list:128) */
extern
void g_cclosure_user_marshal_INT__INT (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:POINTER,STRING,INT (gtkmarshalers.list:129) */
extern
void g_cclosure_user_marshal_VOID__POINTER_STRING_INT (GClosure     *closure,
                                                       GValue       *return_value,
                                                       guint         n_param_values,
                                                       const GValue *param_values,
                                                       gpointer      invocation_hint,
                                                       gpointer      marshal_data);

/* INT:OBJECT,OBJECT,POINTER (gtkmarshalers.list:130) */
extern
void g_cclosure_user_marshal_INT__OBJECT_OBJECT_POINTER (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* VOID:POINTER,POINTER,POINTER,POINTER,STRING (gtkmarshalers.list:131) */
extern
void g_cclosure_user_marshal_VOID__POINTER_POINTER_POINTER_POINTER_STRING (GClosure     *closure,
                                                                           GValue       *return_value,
                                                                           guint         n_param_values,
                                                                           const GValue *param_values,
                                                                           gpointer      invocation_hint,
                                                                           gpointer      marshal_data);


G_END_DECLS

#endif /* __G_CCLOSURE_USER_MARSHAL_MARSHAL_H__ */
